name: file_picker_example
description: An example of how to use the file_picker plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  file_picker:
    path: ../

flutter:
  uses-material-design: true