name: file_picker_example
description: An example of how to use the file_picker plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  file_picker:
    path: ../

flutter:
  uses-material-design: true