name: flutter_file_picker_workspace
description: Root workspace definition for flutter_file_picker repository.
publish_to: none

workspace:
  - packages/file_picker
  - packages/file_picker_platform_interface
  - packages/file_picker_android
  - packages/file_picker_darwin
  - packages/file_picker_linux
  - packages/file_picker_windows
  - packages/file_picker_web
  - packages/file_picker_linux/example
  - example

melos:
  packages:
    - packages/*
    - packages/*/example
    - example
  scripts:
    analyze:
      exec: flutter analyze .
      description: Run flutter analyze in all packages.

    test:
      exec: flutter test
      concurrency: 1
      description: Run flutter test in all packages.

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  melos: ^8.2.2
