name: file_picker_darwin
description: Darwin (iOS and macOS) implementation of the file_picker plugin, supporting native file picking, saving, and directory selection.
version: 1.1.0
homepage: https://github.com/vicajilau/flutter_file_picker/tree/master/packages/file_picker_darwin
repository: https://github.com/vicajilau/flutter_file_picker/tree/master/packages/file_picker_darwin
topics:
  - file-picker
  - ios
  - macos
  - darwin

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: file_picker
    platforms:
      ios:
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerDarwin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  file_picker_platform_interface: ^3.3.0
  cross_file: ^0.3.5+4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
