name: file_picker_linux
description: Linux implementation of the file_picker plugin using GTK3 and XDG Desktop Portals for native file and directory picking.
version: 1.1.0
homepage: https://github.com/miguelpruivo/flutter_file_picker/tree/master/packages/file_picker_linux
repository: https://github.com/miguelpruivo/flutter_file_picker/tree/master/packages/file_picker_linux
topics:
  - file-picker
  - linux

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: file_picker
    platforms:
      linux:
        dartPluginClass: FilePickerLinux

dependencies:
  flutter:
    sdk: flutter
  file_picker_platform_interface: ^3.3.0
  cross_file: ^0.3.5+4
  dbus: ^0.7.13
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
