name: file_picker
description: A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
homepage: https://github.com/miguelpruivo/plugins_flutter_file_picker
version: 1.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.6
  file_picker_platform_interface: ^1.3.1

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.mr.flutter.plugin.filepicker
        pluginClass: FilePickerPlugin
      ios:
        pluginClass: FilePickerPlugin
      web:
        default_package: file_picker_web
