name: file_picker_web
description: Web implementation of the file_picker plugin.
version: 1.0.0
homepage: https://github.com/miguelpruivo/flutter_file_picker/tree/master/packages/file_picker_web
repository: https://github.com/miguelpruivo/flutter_file_picker/tree/master/packages/file_picker_web
topics:
  - file-picker
  - web

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: file_picker
    platforms:
      web:
        pluginClass: FilePickerWeb
        fileName: file_picker_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  file_picker_platform_interface: ^1.0.0
  cross_file: ^0.3.5+4
  meta: ^1.17.0
  path: ^1.9.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
