name: file_picker_platform_interface
description: Platform interface for file_picker.
version: 1.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  cross_file: ^0.3.5+2
  path: ^1.9.1
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
